from sqlalchemy import Column, Integer, String, DateTime
from sqlalchemy.dialects.postgresql import ARRAY

from lhcdb.database import Base

class Input(Base):
    """ Inputs. """

    __tablename__ = 'lhcdb_input_names'

    id = Column(Integer, primary_key=True)
    name = Column(String, unique=True, nullable=False)

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        return '<Input %r>' % (self.name)

class HardwareConnections(Base):
    """ Hardware connections. """

    __tablename__ = 'lhcdb_hardware_connections'

    id = Column(Integer, primary_key=True)
    date_time = Column(DateTime(timezone=False), unique=True, nullable=False)
    date_time_added = Column(
        DateTime(timezone=False), unique=True, nullable=False)
    date_time_updated = Column(
        DateTime(timezone=False), unique=True, nullable=False)

    #date_time_local = Column(
    #    DateTime(timezone=False), unique=True, nullable=False)
    #date_time_utc = Column(
    #    DateTime(timezone=True), unique=True, nullable=False)
    #date_time_local_added = Column(
    #    DateTime(timezone=False), unique=True, nullable=False
    #    )
    #date_time_utc_added = Column(
    #    DateTime(timezone=True), unique=True, nullable=False)

    ## CAEN board 0: CAEN V1740, 64 channels
    #caen_board_0_channel_0 = Column(String, unique=True)
    #caen_board_0_channel_1 = Column(String, unique=True)
    #caen_board_0_channel_2 = Column(String, unique=True)
    #caen_board_0_channel_3 = Column(String, unique=True)
    #caen_board_0_channel_4 = Column(String, unique=True)
    #caen_board_0_channel_5 = Column(String, unique=True)
    #caen_board_0_channel_6 = Column(String, unique=True)
    #caen_board_0_channel_7 = Column(String, unique=True)
    #caen_board_0_channel_8 = Column(String, unique=True)
    #caen_board_0_channel_9 = Column(String, unique=True)
    #caen_board_0_channel_10 = Column(String, unique=True)
    #caen_board_0_channel_11 = Column(String, unique=True)
    #caen_board_0_channel_12 = Column(String, unique=True)
    #caen_board_0_channel_13 = Column(String, unique=True)
    #caen_board_0_channel_14 = Column(String, unique=True)
    #caen_board_0_channel_15 = Column(String, unique=True)
    #caen_board_0_channel_16 = Column(String, unique=True)
    #caen_board_0_channel_17 = Column(String, unique=True)
    #caen_board_0_channel_18 = Column(String, unique=True)
    #caen_board_0_channel_19 = Column(String, unique=True)
    #caen_board_0_channel_20 = Column(String, unique=True)
    #caen_board_0_channel_21 = Column(String, unique=True)
    #caen_board_0_channel_22 = Column(String, unique=True)
    #caen_board_0_channel_23 = Column(String, unique=True)
    #caen_board_0_channel_24 = Column(String, unique=True)
    #caen_board_0_channel_25 = Column(String, unique=True)
    #caen_board_0_channel_26 = Column(String, unique=True)
    #caen_board_0_channel_27 = Column(String, unique=True)
    #caen_board_0_channel_28 = Column(String, unique=True)
    #caen_board_0_channel_29 = Column(String, unique=True)
    #caen_board_0_channel_30 = Column(String, unique=True)
    #caen_board_0_channel_31 = Column(String, unique=True)
    #caen_board_0_channel_32 = Column(String, unique=True)
    #caen_board_0_channel_33 = Column(String, unique=True)
    #caen_board_0_channel_34 = Column(String, unique=True)
    #caen_board_0_channel_35 = Column(String, unique=True)
    #caen_board_0_channel_36 = Column(String, unique=True)
    #caen_board_0_channel_37 = Column(String, unique=True)
    #caen_board_0_channel_38 = Column(String, unique=True)
    #caen_board_0_channel_39 = Column(String, unique=True)
    #caen_board_0_channel_40 = Column(String, unique=True)
    #caen_board_0_channel_41 = Column(String, unique=True)
    #caen_board_0_channel_42 = Column(String, unique=True)
    #caen_board_0_channel_43 = Column(String, unique=True)
    #caen_board_0_channel_44 = Column(String, unique=True)
    #caen_board_0_channel_45 = Column(String, unique=True)
    #caen_board_0_channel_46 = Column(String, unique=True)
    #caen_board_0_channel_47 = Column(String, unique=True)
    #caen_board_0_channel_48 = Column(String, unique=True)
    #caen_board_0_channel_49 = Column(String, unique=True)
    #caen_board_0_channel_50 = Column(String, unique=True)
    #caen_board_0_channel_51 = Column(String, unique=True)
    #caen_board_0_channel_52 = Column(String, unique=True)
    #caen_board_0_channel_53 = Column(String, unique=True)
    #caen_board_0_channel_54 = Column(String, unique=True)
    #caen_board_0_channel_55 = Column(String, unique=True)
    #caen_board_0_channel_56 = Column(String, unique=True)
    #caen_board_0_channel_57 = Column(String, unique=True)
    #caen_board_0_channel_58 = Column(String, unique=True)
    #caen_board_0_channel_59 = Column(String, unique=True)
    #caen_board_0_channel_60 = Column(String, unique=True)
    #caen_board_0_channel_61 = Column(String, unique=True)
    #caen_board_0_channel_62 = Column(String, unique=True)
    #caen_board_0_channel_63 = Column(String, unique=True)

    ## CAEN board 1: CAEN V1740, 64 channels
    #caen_board_1_channel_0 = Column(String, unique=True)
    #caen_board_1_channel_1 = Column(String, unique=True)
    #caen_board_1_channel_2 = Column(String, unique=True)
    #caen_board_1_channel_3 = Column(String, unique=True)
    #caen_board_1_channel_4 = Column(String, unique=True)
    #caen_board_1_channel_5 = Column(String, unique=True)
    #caen_board_1_channel_6 = Column(String, unique=True)
    #caen_board_1_channel_7 = Column(String, unique=True)
    #caen_board_1_channel_8 = Column(String, unique=True)
    #caen_board_1_channel_9 = Column(String, unique=True)
    #caen_board_1_channel_10 = Column(String, unique=True)
    #caen_board_1_channel_11 = Column(String, unique=True)
    #caen_board_1_channel_12 = Column(String, unique=True)
    #caen_board_1_channel_13 = Column(String, unique=True)
    #caen_board_1_channel_14 = Column(String, unique=True)
    #caen_board_1_channel_15 = Column(String, unique=True)
    #caen_board_1_channel_16 = Column(String, unique=True)
    #caen_board_1_channel_17 = Column(String, unique=True)
    #caen_board_1_channel_18 = Column(String, unique=True)
    #caen_board_1_channel_19 = Column(String, unique=True)
    #caen_board_1_channel_20 = Column(String, unique=True)
    #caen_board_1_channel_21 = Column(String, unique=True)
    #caen_board_1_channel_22 = Column(String, unique=True)
    #caen_board_1_channel_23 = Column(String, unique=True)
    #caen_board_1_channel_24 = Column(String, unique=True)
    #caen_board_1_channel_25 = Column(String, unique=True)
    #caen_board_1_channel_26 = Column(String, unique=True)
    #caen_board_1_channel_27 = Column(String, unique=True)
    #caen_board_1_channel_28 = Column(String, unique=True)
    #caen_board_1_channel_29 = Column(String, unique=True)
    #caen_board_1_channel_30 = Column(String, unique=True)
    #caen_board_1_channel_31 = Column(String, unique=True)
    #caen_board_1_channel_32 = Column(String, unique=True)
    #caen_board_1_channel_33 = Column(String, unique=True)
    #caen_board_1_channel_34 = Column(String, unique=True)
    #caen_board_1_channel_35 = Column(String, unique=True)
    #caen_board_1_channel_36 = Column(String, unique=True)
    #caen_board_1_channel_37 = Column(String, unique=True)
    #caen_board_1_channel_38 = Column(String, unique=True)
    #caen_board_1_channel_39 = Column(String, unique=True)
    #caen_board_1_channel_40 = Column(String, unique=True)
    #caen_board_1_channel_41 = Column(String, unique=True)
    #caen_board_1_channel_42 = Column(String, unique=True)
    #caen_board_1_channel_43 = Column(String, unique=True)
    #caen_board_1_channel_44 = Column(String, unique=True)
    #caen_board_1_channel_45 = Column(String, unique=True)
    #caen_board_1_channel_46 = Column(String, unique=True)
    #caen_board_1_channel_47 = Column(String, unique=True)
    #caen_board_1_channel_48 = Column(String, unique=True)
    #caen_board_1_channel_49 = Column(String, unique=True)
    #caen_board_1_channel_50 = Column(String, unique=True)
    #caen_board_1_channel_51 = Column(String, unique=True)
    #caen_board_1_channel_52 = Column(String, unique=True)
    #caen_board_1_channel_53 = Column(String, unique=True)
    #caen_board_1_channel_54 = Column(String, unique=True)
    #caen_board_1_channel_55 = Column(String, unique=True)
    #caen_board_1_channel_56 = Column(String, unique=True)
    #caen_board_1_channel_57 = Column(String, unique=True)
    #caen_board_1_channel_58 = Column(String, unique=True)
    #caen_board_1_channel_59 = Column(String, unique=True)
    #caen_board_1_channel_60 = Column(String, unique=True)
    #caen_board_1_channel_61 = Column(String, unique=True)
    #caen_board_1_channel_62 = Column(String, unique=True)
    #caen_board_1_channel_63 = Column(String, unique=True)

    ## CAEN board 2: CAEN V1740, 64 channels
    #caen_board_2_channel_0 = Column(String, unique=True)
    #caen_board_2_channel_1 = Column(String, unique=True)
    #caen_board_2_channel_2 = Column(String, unique=True)
    #caen_board_2_channel_3 = Column(String, unique=True)
    #caen_board_2_channel_4 = Column(String, unique=True)
    #caen_board_2_channel_5 = Column(String, unique=True)
    #caen_board_2_channel_6 = Column(String, unique=True)
    #caen_board_2_channel_7 = Column(String, unique=True)
    #caen_board_2_channel_8 = Column(String, unique=True)
    #caen_board_2_channel_9 = Column(String, unique=True)
    #caen_board_2_channel_10 = Column(String, unique=True)
    #caen_board_2_channel_11 = Column(String, unique=True)
    #caen_board_2_channel_12 = Column(String, unique=True)
    #caen_board_2_channel_13 = Column(String, unique=True)
    #caen_board_2_channel_14 = Column(String, unique=True)
    #caen_board_2_channel_15 = Column(String, unique=True)
    #caen_board_2_channel_16 = Column(String, unique=True)
    #caen_board_2_channel_17 = Column(String, unique=True)
    #caen_board_2_channel_18 = Column(String, unique=True)
    #caen_board_2_channel_19 = Column(String, unique=True)
    #caen_board_2_channel_20 = Column(String, unique=True)
    #caen_board_2_channel_21 = Column(String, unique=True)
    #caen_board_2_channel_22 = Column(String, unique=True)
    #caen_board_2_channel_23 = Column(String, unique=True)
    #caen_board_2_channel_24 = Column(String, unique=True)
    #caen_board_2_channel_25 = Column(String, unique=True)
    #caen_board_2_channel_26 = Column(String, unique=True)
    #caen_board_2_channel_27 = Column(String, unique=True)
    #caen_board_2_channel_28 = Column(String, unique=True)
    #caen_board_2_channel_29 = Column(String, unique=True)
    #caen_board_2_channel_30 = Column(String, unique=True)
    #caen_board_2_channel_31 = Column(String, unique=True)
    #caen_board_2_channel_32 = Column(String, unique=True)
    #caen_board_2_channel_33 = Column(String, unique=True)
    #caen_board_2_channel_34 = Column(String, unique=True)
    #caen_board_2_channel_35 = Column(String, unique=True)
    #caen_board_2_channel_36 = Column(String, unique=True)
    #caen_board_2_channel_37 = Column(String, unique=True)
    #caen_board_2_channel_38 = Column(String, unique=True)
    #caen_board_2_channel_39 = Column(String, unique=True)
    #caen_board_2_channel_40 = Column(String, unique=True)
    #caen_board_2_channel_41 = Column(String, unique=True)
    #caen_board_2_channel_42 = Column(String, unique=True)
    #caen_board_2_channel_43 = Column(String, unique=True)
    #caen_board_2_channel_44 = Column(String, unique=True)
    #caen_board_2_channel_45 = Column(String, unique=True)
    #caen_board_2_channel_46 = Column(String, unique=True)
    #caen_board_2_channel_47 = Column(String, unique=True)
    #caen_board_2_channel_48 = Column(String, unique=True)
    #caen_board_2_channel_49 = Column(String, unique=True)
    #caen_board_2_channel_50 = Column(String, unique=True)
    #caen_board_2_channel_51 = Column(String, unique=True)
    #caen_board_2_channel_52 = Column(String, unique=True)
    #caen_board_2_channel_53 = Column(String, unique=True)
    #caen_board_2_channel_54 = Column(String, unique=True)
    #caen_board_2_channel_55 = Column(String, unique=True)
    #caen_board_2_channel_56 = Column(String, unique=True)
    #caen_board_2_channel_57 = Column(String, unique=True)
    #caen_board_2_channel_58 = Column(String, unique=True)
    #caen_board_2_channel_59 = Column(String, unique=True)
    #caen_board_2_channel_60 = Column(String, unique=True)
    #caen_board_2_channel_61 = Column(String, unique=True)
    #caen_board_2_channel_62 = Column(String, unique=True)
    #caen_board_2_channel_63 = Column(String, unique=True)

    ## CAEN board 3: CAEN V1740, 64 channels
    #caen_board_3_channel_0 = Column(String, unique=True)
    #caen_board_3_channel_1 = Column(String, unique=True)
    #caen_board_3_channel_2 = Column(String, unique=True)
    #caen_board_3_channel_3 = Column(String, unique=True)
    #caen_board_3_channel_4 = Column(String, unique=True)
    #caen_board_3_channel_5 = Column(String, unique=True)
    #caen_board_3_channel_6 = Column(String, unique=True)
    #caen_board_3_channel_7 = Column(String, unique=True)
    #caen_board_3_channel_8 = Column(String, unique=True)
    #caen_board_3_channel_9 = Column(String, unique=True)
    #caen_board_3_channel_10 = Column(String, unique=True)
    #caen_board_3_channel_11 = Column(String, unique=True)
    #caen_board_3_channel_12 = Column(String, unique=True)
    #caen_board_3_channel_13 = Column(String, unique=True)
    #caen_board_3_channel_14 = Column(String, unique=True)
    #caen_board_3_channel_15 = Column(String, unique=True)
    #caen_board_3_channel_16 = Column(String, unique=True)
    #caen_board_3_channel_17 = Column(String, unique=True)
    #caen_board_3_channel_18 = Column(String, unique=True)
    #caen_board_3_channel_19 = Column(String, unique=True)
    #caen_board_3_channel_20 = Column(String, unique=True)
    #caen_board_3_channel_21 = Column(String, unique=True)
    #caen_board_3_channel_22 = Column(String, unique=True)
    #caen_board_3_channel_23 = Column(String, unique=True)
    #caen_board_3_channel_24 = Column(String, unique=True)
    #caen_board_3_channel_25 = Column(String, unique=True)
    #caen_board_3_channel_26 = Column(String, unique=True)
    #caen_board_3_channel_27 = Column(String, unique=True)
    #caen_board_3_channel_28 = Column(String, unique=True)
    #caen_board_3_channel_29 = Column(String, unique=True)
    #caen_board_3_channel_30 = Column(String, unique=True)
    #caen_board_3_channel_31 = Column(String, unique=True)
    #caen_board_3_channel_32 = Column(String, unique=True)
    #caen_board_3_channel_33 = Column(String, unique=True)
    #caen_board_3_channel_34 = Column(String, unique=True)
    #caen_board_3_channel_35 = Column(String, unique=True)
    #caen_board_3_channel_36 = Column(String, unique=True)
    #caen_board_3_channel_37 = Column(String, unique=True)
    #caen_board_3_channel_38 = Column(String, unique=True)
    #caen_board_3_channel_39 = Column(String, unique=True)
    #caen_board_3_channel_40 = Column(String, unique=True)
    #caen_board_3_channel_41 = Column(String, unique=True)
    #caen_board_3_channel_42 = Column(String, unique=True)
    #caen_board_3_channel_43 = Column(String, unique=True)
    #caen_board_3_channel_44 = Column(String, unique=True)
    #caen_board_3_channel_45 = Column(String, unique=True)
    #caen_board_3_channel_46 = Column(String, unique=True)
    #caen_board_3_channel_47 = Column(String, unique=True)
    #caen_board_3_channel_48 = Column(String, unique=True)
    #caen_board_3_channel_49 = Column(String, unique=True)
    #caen_board_3_channel_50 = Column(String, unique=True)
    #caen_board_3_channel_51 = Column(String, unique=True)
    #caen_board_3_channel_52 = Column(String, unique=True)
    #caen_board_3_channel_53 = Column(String, unique=True)
    #caen_board_3_channel_54 = Column(String, unique=True)
    #caen_board_3_channel_55 = Column(String, unique=True)
    #caen_board_3_channel_56 = Column(String, unique=True)
    #caen_board_3_channel_57 = Column(String, unique=True)
    #caen_board_3_channel_58 = Column(String, unique=True)
    #caen_board_3_channel_59 = Column(String, unique=True)
    #caen_board_3_channel_60 = Column(String, unique=True)
    #caen_board_3_channel_61 = Column(String, unique=True)
    #caen_board_3_channel_62 = Column(String, unique=True)
    #caen_board_3_channel_63 = Column(String, unique=True)

    ## CAEN board 4: CAEN V1740, 64 channels
    #caen_board_4_channel_0 = Column(String, unique=True)
    #caen_board_4_channel_1 = Column(String, unique=True)
    #caen_board_4_channel_2 = Column(String, unique=True)
    #caen_board_4_channel_3 = Column(String, unique=True)
    #caen_board_4_channel_4 = Column(String, unique=True)
    #caen_board_4_channel_5 = Column(String, unique=True)
    #caen_board_4_channel_6 = Column(String, unique=True)
    #caen_board_4_channel_7 = Column(String, unique=True)
    #caen_board_4_channel_8 = Column(String, unique=True)
    #caen_board_4_channel_9 = Column(String, unique=True)
    #caen_board_4_channel_10 = Column(String, unique=True)
    #caen_board_4_channel_11 = Column(String, unique=True)
    #caen_board_4_channel_12 = Column(String, unique=True)
    #caen_board_4_channel_13 = Column(String, unique=True)
    #caen_board_4_channel_14 = Column(String, unique=True)
    #caen_board_4_channel_15 = Column(String, unique=True)
    #caen_board_4_channel_16 = Column(String, unique=True)
    #caen_board_4_channel_17 = Column(String, unique=True)
    #caen_board_4_channel_18 = Column(String, unique=True)
    #caen_board_4_channel_19 = Column(String, unique=True)
    #caen_board_4_channel_20 = Column(String, unique=True)
    #caen_board_4_channel_21 = Column(String, unique=True)
    #caen_board_4_channel_22 = Column(String, unique=True)
    #caen_board_4_channel_23 = Column(String, unique=True)
    #caen_board_4_channel_24 = Column(String, unique=True)
    #caen_board_4_channel_25 = Column(String, unique=True)
    #caen_board_4_channel_26 = Column(String, unique=True)
    #caen_board_4_channel_27 = Column(String, unique=True)
    #caen_board_4_channel_28 = Column(String, unique=True)
    #caen_board_4_channel_29 = Column(String, unique=True)
    #caen_board_4_channel_30 = Column(String, unique=True)
    #caen_board_4_channel_31 = Column(String, unique=True)
    #caen_board_4_channel_32 = Column(String, unique=True)
    #caen_board_4_channel_33 = Column(String, unique=True)
    #caen_board_4_channel_34 = Column(String, unique=True)
    #caen_board_4_channel_35 = Column(String, unique=True)
    #caen_board_4_channel_36 = Column(String, unique=True)
    #caen_board_4_channel_37 = Column(String, unique=True)
    #caen_board_4_channel_38 = Column(String, unique=True)
    #caen_board_4_channel_39 = Column(String, unique=True)
    #caen_board_4_channel_40 = Column(String, unique=True)
    #caen_board_4_channel_41 = Column(String, unique=True)
    #caen_board_4_channel_42 = Column(String, unique=True)
    #caen_board_4_channel_43 = Column(String, unique=True)
    #caen_board_4_channel_44 = Column(String, unique=True)
    #caen_board_4_channel_45 = Column(String, unique=True)
    #caen_board_4_channel_46 = Column(String, unique=True)
    #caen_board_4_channel_47 = Column(String, unique=True)
    #caen_board_4_channel_48 = Column(String, unique=True)
    #caen_board_4_channel_49 = Column(String, unique=True)
    #caen_board_4_channel_50 = Column(String, unique=True)
    #caen_board_4_channel_51 = Column(String, unique=True)
    #caen_board_4_channel_52 = Column(String, unique=True)
    #caen_board_4_channel_53 = Column(String, unique=True)
    #caen_board_4_channel_54 = Column(String, unique=True)
    #caen_board_4_channel_55 = Column(String, unique=True)
    #caen_board_4_channel_56 = Column(String, unique=True)
    #caen_board_4_channel_57 = Column(String, unique=True)
    #caen_board_4_channel_58 = Column(String, unique=True)
    #caen_board_4_channel_59 = Column(String, unique=True)
    #caen_board_4_channel_60 = Column(String, unique=True)
    #caen_board_4_channel_61 = Column(String, unique=True)
    #caen_board_4_channel_62 = Column(String, unique=True)
    #caen_board_4_channel_63 = Column(String, unique=True)

    ## CAEN board 5: CAEN V1740, 64 channels
    #caen_board_5_channel_0 = Column(String, unique=True)
    #caen_board_5_channel_1 = Column(String, unique=True)
    #caen_board_5_channel_2 = Column(String, unique=True)
    #caen_board_5_channel_3 = Column(String, unique=True)
    #caen_board_5_channel_4 = Column(String, unique=True)
    #caen_board_5_channel_5 = Column(String, unique=True)
    #caen_board_5_channel_6 = Column(String, unique=True)
    #caen_board_5_channel_7 = Column(String, unique=True)
    #caen_board_5_channel_8 = Column(String, unique=True)
    #caen_board_5_channel_9 = Column(String, unique=True)
    #caen_board_5_channel_10 = Column(String, unique=True)
    #caen_board_5_channel_11 = Column(String, unique=True)
    #caen_board_5_channel_12 = Column(String, unique=True)
    #caen_board_5_channel_13 = Column(String, unique=True)
    #caen_board_5_channel_14 = Column(String, unique=True)
    #caen_board_5_channel_15 = Column(String, unique=True)
    #caen_board_5_channel_16 = Column(String, unique=True)
    #caen_board_5_channel_17 = Column(String, unique=True)
    #caen_board_5_channel_18 = Column(String, unique=True)
    #caen_board_5_channel_19 = Column(String, unique=True)
    #caen_board_5_channel_20 = Column(String, unique=True)
    #caen_board_5_channel_21 = Column(String, unique=True)
    #caen_board_5_channel_22 = Column(String, unique=True)
    #caen_board_5_channel_23 = Column(String, unique=True)
    #caen_board_5_channel_24 = Column(String, unique=True)
    #caen_board_5_channel_25 = Column(String, unique=True)
    #caen_board_5_channel_26 = Column(String, unique=True)
    #caen_board_5_channel_27 = Column(String, unique=True)
    #caen_board_5_channel_28 = Column(String, unique=True)
    #caen_board_5_channel_29 = Column(String, unique=True)
    #caen_board_5_channel_30 = Column(String, unique=True)
    #caen_board_5_channel_31 = Column(String, unique=True)
    #caen_board_5_channel_32 = Column(String, unique=True)
    #caen_board_5_channel_33 = Column(String, unique=True)
    #caen_board_5_channel_34 = Column(String, unique=True)
    #caen_board_5_channel_35 = Column(String, unique=True)
    #caen_board_5_channel_36 = Column(String, unique=True)
    #caen_board_5_channel_37 = Column(String, unique=True)
    #caen_board_5_channel_38 = Column(String, unique=True)
    #caen_board_5_channel_39 = Column(String, unique=True)
    #caen_board_5_channel_40 = Column(String, unique=True)
    #caen_board_5_channel_41 = Column(String, unique=True)
    #caen_board_5_channel_42 = Column(String, unique=True)
    #caen_board_5_channel_43 = Column(String, unique=True)
    #caen_board_5_channel_44 = Column(String, unique=True)
    #caen_board_5_channel_45 = Column(String, unique=True)
    #caen_board_5_channel_46 = Column(String, unique=True)
    #caen_board_5_channel_47 = Column(String, unique=True)
    #caen_board_5_channel_48 = Column(String, unique=True)
    #caen_board_5_channel_49 = Column(String, unique=True)
    #caen_board_5_channel_50 = Column(String, unique=True)
    #caen_board_5_channel_51 = Column(String, unique=True)
    #caen_board_5_channel_52 = Column(String, unique=True)
    #caen_board_5_channel_53 = Column(String, unique=True)
    #caen_board_5_channel_54 = Column(String, unique=True)
    #caen_board_5_channel_55 = Column(String, unique=True)
    #caen_board_5_channel_56 = Column(String, unique=True)
    #caen_board_5_channel_57 = Column(String, unique=True)
    #caen_board_5_channel_58 = Column(String, unique=True)
    #caen_board_5_channel_59 = Column(String, unique=True)
    #caen_board_5_channel_60 = Column(String, unique=True)
    #caen_board_5_channel_61 = Column(String, unique=True)
    #caen_board_5_channel_62 = Column(String, unique=True)
    #caen_board_5_channel_63 = Column(String, unique=True)

    ## CAEN board 6: CAEN V1740, 64 channels
    #caen_board_6_channel_0 = Column(String, unique=True)
    #caen_board_6_channel_1 = Column(String, unique=True)
    #caen_board_6_channel_2 = Column(String, unique=True)
    #caen_board_6_channel_3 = Column(String, unique=True)
    #caen_board_6_channel_4 = Column(String, unique=True)
    #caen_board_6_channel_5 = Column(String, unique=True)
    #caen_board_6_channel_6 = Column(String, unique=True)
    #caen_board_6_channel_7 = Column(String, unique=True)
    #caen_board_6_channel_8 = Column(String, unique=True)
    #caen_board_6_channel_9 = Column(String, unique=True)
    #caen_board_6_channel_10 = Column(String, unique=True)
    #caen_board_6_channel_11 = Column(String, unique=True)
    #caen_board_6_channel_12 = Column(String, unique=True)
    #caen_board_6_channel_13 = Column(String, unique=True)
    #caen_board_6_channel_14 = Column(String, unique=True)
    #caen_board_6_channel_15 = Column(String, unique=True)
    #caen_board_6_channel_16 = Column(String, unique=True)
    #caen_board_6_channel_17 = Column(String, unique=True)
    #caen_board_6_channel_18 = Column(String, unique=True)
    #caen_board_6_channel_19 = Column(String, unique=True)
    #caen_board_6_channel_20 = Column(String, unique=True)
    #caen_board_6_channel_21 = Column(String, unique=True)
    #caen_board_6_channel_22 = Column(String, unique=True)
    #caen_board_6_channel_23 = Column(String, unique=True)
    #caen_board_6_channel_24 = Column(String, unique=True)
    #caen_board_6_channel_25 = Column(String, unique=True)
    #caen_board_6_channel_26 = Column(String, unique=True)
    #caen_board_6_channel_27 = Column(String, unique=True)
    #caen_board_6_channel_28 = Column(String, unique=True)
    #caen_board_6_channel_29 = Column(String, unique=True)
    #caen_board_6_channel_30 = Column(String, unique=True)
    #caen_board_6_channel_31 = Column(String, unique=True)
    #caen_board_6_channel_32 = Column(String, unique=True)
    #caen_board_6_channel_33 = Column(String, unique=True)
    #caen_board_6_channel_34 = Column(String, unique=True)
    #caen_board_6_channel_35 = Column(String, unique=True)
    #caen_board_6_channel_36 = Column(String, unique=True)
    #caen_board_6_channel_37 = Column(String, unique=True)
    #caen_board_6_channel_38 = Column(String, unique=True)
    #caen_board_6_channel_39 = Column(String, unique=True)
    #caen_board_6_channel_40 = Column(String, unique=True)
    #caen_board_6_channel_41 = Column(String, unique=True)
    #caen_board_6_channel_42 = Column(String, unique=True)
    #caen_board_6_channel_43 = Column(String, unique=True)
    #caen_board_6_channel_44 = Column(String, unique=True)
    #caen_board_6_channel_45 = Column(String, unique=True)
    #caen_board_6_channel_46 = Column(String, unique=True)
    #caen_board_6_channel_47 = Column(String, unique=True)
    #caen_board_6_channel_48 = Column(String, unique=True)
    #caen_board_6_channel_49 = Column(String, unique=True)
    #caen_board_6_channel_50 = Column(String, unique=True)
    #caen_board_6_channel_51 = Column(String, unique=True)
    #caen_board_6_channel_52 = Column(String, unique=True)
    #caen_board_6_channel_53 = Column(String, unique=True)
    #caen_board_6_channel_54 = Column(String, unique=True)
    #caen_board_6_channel_55 = Column(String, unique=True)
    #caen_board_6_channel_56 = Column(String, unique=True)
    #caen_board_6_channel_57 = Column(String, unique=True)
    #caen_board_6_channel_58 = Column(String, unique=True)
    #caen_board_6_channel_59 = Column(String, unique=True)
    #caen_board_6_channel_60 = Column(String, unique=True)
    #caen_board_6_channel_61 = Column(String, unique=True)
    #caen_board_6_channel_62 = Column(String, unique=True)
    #caen_board_6_channel_63 = Column(String, unique=True)

    ## CAEN board 7: CAEN V1740, 64 channels
    #caen_board_7_channel_0 = Column(String, unique=True)
    #caen_board_7_channel_1 = Column(String, unique=True)
    #caen_board_7_channel_2 = Column(String, unique=True)
    #caen_board_7_channel_3 = Column(String, unique=True)
    #caen_board_7_channel_4 = Column(String, unique=True)
    #caen_board_7_channel_5 = Column(String, unique=True)
    #caen_board_7_channel_6 = Column(String, unique=True)
    #caen_board_7_channel_7 = Column(String, unique=True)
    #caen_board_7_channel_8 = Column(String, unique=True)
    #caen_board_7_channel_9 = Column(String, unique=True)
    #caen_board_7_channel_10 = Column(String, unique=True)
    #caen_board_7_channel_11 = Column(String, unique=True)
    #caen_board_7_channel_12 = Column(String, unique=True)
    #caen_board_7_channel_13 = Column(String, unique=True)
    #caen_board_7_channel_14 = Column(String, unique=True)
    #caen_board_7_channel_15 = Column(String, unique=True)
    #caen_board_7_channel_16 = Column(String, unique=True)
    #caen_board_7_channel_17 = Column(String, unique=True)
    #caen_board_7_channel_18 = Column(String, unique=True)
    #caen_board_7_channel_19 = Column(String, unique=True)
    #caen_board_7_channel_20 = Column(String, unique=True)
    #caen_board_7_channel_21 = Column(String, unique=True)
    #caen_board_7_channel_22 = Column(String, unique=True)
    #caen_board_7_channel_23 = Column(String, unique=True)
    #caen_board_7_channel_24 = Column(String, unique=True)
    #caen_board_7_channel_25 = Column(String, unique=True)
    #caen_board_7_channel_26 = Column(String, unique=True)
    #caen_board_7_channel_27 = Column(String, unique=True)
    #caen_board_7_channel_28 = Column(String, unique=True)
    #caen_board_7_channel_29 = Column(String, unique=True)
    #caen_board_7_channel_30 = Column(String, unique=True)
    #caen_board_7_channel_31 = Column(String, unique=True)

    # CAEN board 7: CAEN V1740, 64 channels
    caen_board_7_channel_32 = Column(String, unique=True)
    caen_board_7_channel_33 = Column(String, unique=True)
    caen_board_7_channel_34 = Column(String, unique=True)
    caen_board_7_channel_35 = Column(String, unique=True)
    caen_board_7_channel_36 = Column(String, unique=True)
    caen_board_7_channel_37 = Column(String, unique=True)
    caen_board_7_channel_38 = Column(String, unique=True)
    caen_board_7_channel_39 = Column(String, unique=True)
    caen_board_7_channel_40 = Column(String, unique=True)
    caen_board_7_channel_41 = Column(String, unique=True)
    caen_board_7_channel_42 = Column(String, unique=True)
    caen_board_7_channel_43 = Column(String, unique=True)
    caen_board_7_channel_44 = Column(String, unique=True)
    caen_board_7_channel_45 = Column(String, unique=True)
    caen_board_7_channel_46 = Column(String, unique=True)
    caen_board_7_channel_47 = Column(String, unique=True)
    caen_board_7_channel_48 = Column(String, unique=True)
    caen_board_7_channel_49 = Column(String, unique=True)
    caen_board_7_channel_50 = Column(String, unique=True)
    caen_board_7_channel_51 = Column(String, unique=True)
    caen_board_7_channel_52 = Column(String, unique=True)
    caen_board_7_channel_53 = Column(String, unique=True)
    caen_board_7_channel_54 = Column(String, unique=True)
    caen_board_7_channel_55 = Column(String, unique=True)
    caen_board_7_channel_56 = Column(String, unique=True)
    caen_board_7_channel_57 = Column(String, unique=True)
    caen_board_7_channel_58 = Column(String, unique=True)
    caen_board_7_channel_59 = Column(String, unique=True)
    caen_board_7_channel_60 = Column(String, unique=True)
    caen_board_7_channel_61 = Column(String, unique=True)
    caen_board_7_channel_62 = Column(String, unique=True)
    caen_board_7_channel_63 = Column(String, unique=True)

    # CAEN board 8: CAEN V1751, 8 channels
    caen_board_8_channel_0 = Column(String, unique=True)
    caen_board_8_channel_1 = Column(String, unique=True)
    caen_board_8_channel_2 = Column(String, unique=True)
    caen_board_8_channel_3 = Column(String, unique=True)
    caen_board_8_channel_4 = Column(String, unique=True)
    caen_board_8_channel_5 = Column(String, unique=True)
    caen_board_8_channel_6 = Column(String, unique=True)
    caen_board_8_channel_7 = Column(String, unique=True)

    # CAEN board 9: CAEN V1751, 8 channels
    caen_board_9_channel_0 = Column(String, unique=True)
    caen_board_9_channel_1 = Column(String, unique=True)
    caen_board_9_channel_2 = Column(String, unique=True)
    caen_board_9_channel_3 = Column(String, unique=True)
    caen_board_9_channel_4 = Column(String, unique=True)
    caen_board_9_channel_5 = Column(String, unique=True)
    caen_board_9_channel_6 = Column(String, unique=True)
    caen_board_9_channel_7 = Column(String, unique=True)

    # CAEN board 24: CAEN V1740, 64 channels
    caen_board_24_channel_0 = Column(String, unique=True)
    caen_board_24_channel_1 = Column(String, unique=True)
    caen_board_24_channel_2 = Column(String, unique=True)
    caen_board_24_channel_3 = Column(String, unique=True)
    caen_board_24_channel_4 = Column(String, unique=True)
    caen_board_24_channel_5 = Column(String, unique=True)
    caen_board_24_channel_6 = Column(String, unique=True)
    caen_board_24_channel_7 = Column(String, unique=True)
    caen_board_24_channel_8 = Column(String, unique=True)
    caen_board_24_channel_9 = Column(String, unique=True)
    caen_board_24_channel_10 = Column(String, unique=True)
    caen_board_24_channel_11 = Column(String, unique=True)
    caen_board_24_channel_12 = Column(String, unique=True)
    caen_board_24_channel_13 = Column(String, unique=True)
    caen_board_24_channel_14 = Column(String, unique=True)
    caen_board_24_channel_15 = Column(String, unique=True)
    caen_board_24_channel_16 = Column(String, unique=True)
    caen_board_24_channel_17 = Column(String, unique=True)
    caen_board_24_channel_18 = Column(String, unique=True)
    caen_board_24_channel_19 = Column(String, unique=True)
    caen_board_24_channel_20 = Column(String, unique=True)
    caen_board_24_channel_21 = Column(String, unique=True)
    caen_board_24_channel_22 = Column(String, unique=True)
    caen_board_24_channel_23 = Column(String, unique=True)
    caen_board_24_channel_24 = Column(String, unique=True)
    caen_board_24_channel_25 = Column(String, unique=True)
    caen_board_24_channel_26 = Column(String, unique=True)
    caen_board_24_channel_27 = Column(String, unique=True)
    caen_board_24_channel_28 = Column(String, unique=True)
    caen_board_24_channel_29 = Column(String, unique=True)
    caen_board_24_channel_30 = Column(String, unique=True)
    caen_board_24_channel_31 = Column(String, unique=True)
    caen_board_24_channel_32 = Column(String, unique=True)
    caen_board_24_channel_33 = Column(String, unique=True)
    caen_board_24_channel_34 = Column(String, unique=True)
    caen_board_24_channel_35 = Column(String, unique=True)
    caen_board_24_channel_36 = Column(String, unique=True)
    caen_board_24_channel_37 = Column(String, unique=True)
    caen_board_24_channel_38 = Column(String, unique=True)
    caen_board_24_channel_39 = Column(String, unique=True)
    caen_board_24_channel_40 = Column(String, unique=True)
    caen_board_24_channel_41 = Column(String, unique=True)
    caen_board_24_channel_42 = Column(String, unique=True)
    caen_board_24_channel_43 = Column(String, unique=True)
    caen_board_24_channel_44 = Column(String, unique=True)
    caen_board_24_channel_45 = Column(String, unique=True)
    caen_board_24_channel_46 = Column(String, unique=True)
    caen_board_24_channel_47 = Column(String, unique=True)
    caen_board_24_channel_48 = Column(String, unique=True)
    caen_board_24_channel_49 = Column(String, unique=True)
    caen_board_24_channel_50 = Column(String, unique=True)
    caen_board_24_channel_51 = Column(String, unique=True)
    caen_board_24_channel_52 = Column(String, unique=True)
    caen_board_24_channel_53 = Column(String, unique=True)
    caen_board_24_channel_54 = Column(String, unique=True)
    caen_board_24_channel_55 = Column(String, unique=True)
    caen_board_24_channel_56 = Column(String, unique=True)
    caen_board_24_channel_57 = Column(String, unique=True)
    caen_board_24_channel_58 = Column(String, unique=True)
    caen_board_24_channel_59 = Column(String, unique=True)
    caen_board_24_channel_60 = Column(String, unique=True)
    caen_board_24_channel_61 = Column(String, unique=True)
    caen_board_24_channel_62 = Column(String, unique=True)
    caen_board_24_channel_63 = Column(String, unique=True)

    def __init__(self, date_time, date_time_added):
        self.date_time = date_time
        self.date_time_added = date_time_added
        self.date_time_updated = date_time_added

    def __repr__(self):
        return '<HardwareConnections %r>' % (self.date_time)

#class HardwareConnections(Base):
#    """ Hardware connections. """
#
#    __tablename__ = 'lhcdb_hardware_connections'
#
#    id = Column(Integer, primary_key=True)
#    index = Column(Integer, unique=True, nullable=False)
#    date_time = Column(DateTime(timezone=False), unique=True, nullable=False)
#    date_time_added = Column(
#        DateTime(timezone=False), unique=True, nullable=False)
#    date_time_updated = Column(
#        DateTime(timezone=False), unique=True, nullable=False)
#
#    def __init__(self, index, date_time, date_time_added):
#        self.index = index
#        self.date_time = date_time
#        self.date_time_added = date_time_added
#        self.date_time_updated = date_time_added
#
#    def __repr__(self):
#        return '<HardwaveConnections %r>' % (self.index)

#class CAENDigitizerInput(Base):
#    """ CAEN digitizer input. """
#
#    __tablename__ = 'lhcdb_caen_digitizer_inputs'
#
#    id = Column(Integer, primary_key=True)
#    indices = Column(MutableList.as_mutable(ARRAY(Integer)))
#    #index = Column(Integer, nullable=False)
#    board_id = Column(Integer, nullable=False)
#    channel = Column(Integer, nullable=False)
#    input_name = Column(String, unique=False)
#    #date_time = Column(DateTime(timezone=False), unique=True, nullable=False)
#    #date_time_added = Column(
#    #    DateTime(timezone=False), unique=True, nullable=False)
#    #date_time_updated = Column(
#    #    DateTime(timezone=False), unique=True, nullable=False)
#
#    def __init__(self, index, board_id, channel, input_name):
#        self.indices = [ index ]
#        self.board_id = board_id
#        self.channel = channel
#        self.input_name = input_name
#        #self.date_time = date_time
#
#    def __repr__(self):
#        return '<CAENDigitizerInput %r %r>' % (self.board_id, self.channel)
#class CAENV1740(Base):
#
#    __tablename__ = 'lhcdb_caen_v1740'
#
#    id = Column(Integer, primary_key=True)
#    board_id = Column(Integer, nullable=False)
#    date_time = Column(DateTime(timezone=False), unique=True, nullable=False)
#    date_time_added = Column(
#        DateTime(timezone=False), unique=True, nullable=False)
#
#    channel_0 = Column(String, unique=True)
#    channel_1 = Column(String, unique=True)
#    channel_2 = Column(String, unique=True)
#    channel_3 = Column(String, unique=True)
#    channel_4 = Column(String, unique=True)
#    channel_5 = Column(String, unique=True)
#    channel_6 = Column(String, unique=True)
#    channel_7 = Column(String, unique=True)
#    channel_8 = Column(String, unique=True)
#    channel_9 = Column(String, unique=True)
#    channel_10 = Column(String, unique=True)
#    channel_11 = Column(String, unique=True)
#    channel_12 = Column(String, unique=True)
#    channel_13 = Column(String, unique=True)
#    channel_14 = Column(String, unique=True)
#    channel_15 = Column(String, unique=True)
#    channel_16 = Column(String, unique=True)
#    channel_17 = Column(String, unique=True)
#    channel_18 = Column(String, unique=True)
#    channel_19 = Column(String, unique=True)
#    channel_20 = Column(String, unique=True)
#    channel_21 = Column(String, unique=True)
#    channel_22 = Column(String, unique=True)
#    channel_23 = Column(String, unique=True)
#    channel_24 = Column(String, unique=True)
#    channel_25 = Column(String, unique=True)
#    channel_26 = Column(String, unique=True)
#    channel_27 = Column(String, unique=True)
#    channel_28 = Column(String, unique=True)
#    channel_29 = Column(String, unique=True)
#    channel_30 = Column(String, unique=True)
#    channel_31 = Column(String, unique=True)
#    channel_32 = Column(String, unique=True)
#    channel_33 = Column(String, unique=True)
#    channel_34 = Column(String, unique=True)
#    channel_35 = Column(String, unique=True)
#    channel_36 = Column(String, unique=True)
#    channel_37 = Column(String, unique=True)
#    channel_38 = Column(String, unique=True)
#    channel_39 = Column(String, unique=True)
#    channel_40 = Column(String, unique=True)
#    channel_41 = Column(String, unique=True)
#    channel_42 = Column(String, unique=True)
#    channel_43 = Column(String, unique=True)
#    channel_44 = Column(String, unique=True)
#    channel_45 = Column(String, unique=True)
#    channel_46 = Column(String, unique=True)
#    channel_47 = Column(String, unique=True)
#    channel_48 = Column(String, unique=True)
#    channel_49 = Column(String, unique=True)
#    channel_50 = Column(String, unique=True)
#    channel_51 = Column(String, unique=True)
#    channel_52 = Column(String, unique=True)
#    channel_53 = Column(String, unique=True)
#    channel_54 = Column(String, unique=True)
#    channel_55 = Column(String, unique=True)
#    channel_56 = Column(String, unique=True)
#    channel_57 = Column(String, unique=True)
#    channel_58 = Column(String, unique=True)
#    channel_59 = Column(String, unique=True)
#    channel_60 = Column(String, unique=True)
#    channel_61 = Column(String, unique=True)
#    channel_62 = Column(String, unique=True)
#    channel_63 = Column(String, unique=True)
#
#    def __init__(self, board_id):
#        self.board_id = board_id
#
#    def __repr__(self):
#        return '<CAENV1740 %r>' % (self.name)

#class CAENV1751(Base):
#
#    __tablename__ = 'lhcdb_caen_v1751'
#
#    id = Column(Integer, primary_key=True)
#    board_id = Column(Integer, nullable=False)
#   date_time = Column(DateTime(timezone=False), unique=True, nullable=False)
#   date_time_added = Column(
#       DateTime(timezone=False), unique=True, nullable=False)
#
#    channel_0 = Column(String, unique=True)
#    channel_1 = Column(String, unique=True)
#    channel_2 = Column(String, unique=True)
#    channel_3 = Column(String, unique=True)
#    channel_4 = Column(String, unique=True)
#    channel_5 = Column(String, unique=True)
#    channel_6 = Column(String, unique=True)
#    channel_7 = Column(String, unique=True)
#    channel_8 = Column(String, unique=True)
#
#    def __init__(self, board_id):
#        self.board_id = board_id
#
#    def __repr__(self):
#        return '<CAENV1751 %r>' % (self.name)

